# Generated by Django 6.1.1 on 2026-09-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        ('users', '0002_user_groups_user_user_permissions_hostprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_space', to='users.hostprofile'),
        ),
        migrations.AddField(
            model_name='spaceimage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.space'),
        ),
    ]
