# Generated by Django 6.1.1 on 2026-09-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_user_permissions_hostprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostprofile',
            old_name='display_name',
            new_name='name',
        ),
    ]
